In [2]:
from scipy.linalg import solve_continuous_are
import numpy as np

In [3]:
g = 9.81
A = np.array([[0, 1, 0, 0], [-2*g, 0, g, 0], [0, 0, 0, 1], [2*g, 0, -2*g, 0]])

In [10]:
B = np.array([[0, -1, 0, 2]]).T

In [16]:
Q = np.eye(4)
R = np.array([[1]])

In [17]:
S = solve_continuous_are(a = A, b = B, q = Q, r = R)

In [18]:
K = -np.linalg.inv(R) @ B.T @ S

In [ ]:
from scipy.linalg import solve_continuous_are
import numpy as np

g = 9.81
A = np.array([[0, 1, 0, 0], [-2*g, 0, g, 0], [0, 0, 0, 1], [2*g, 0, -2*g, 0]])
B = np.array([[0, -1, 0, 2]]).T
Q = np.eye(4)
R = np.array([[1]])

S = solve_continuous_are(a = A, b = B, q = Q, r = R)
K = -np.linalg.inv(R) @ B.T @ S
print("S:", S)
print("K:", K)

S: [[26.4654085  -0.49842744  0.55300996 -0.5166224 ]
 [-0.49842744  2.7569379   0.58842553  1.40650967]
 [ 0.55300996  0.58842553 12.62519166  0.31963111]
 [-0.5166224   1.40650967  0.31963111  1.34342322]]
K: [[ 0.53481736 -0.05608144 -0.05083668 -1.28033676]]


S